### ISSUE TITLE
Forked hardhat node becomes unresponsive when connecting with Metamask

### ISSUE THREAD

**Issue by aliveli186** [NomicFoundation/hardhat#2380]
After upgrading to v2.8.4 I started to receive this error.
How can I increase the memory size?

```
<--- Last few GCs --->

[2096:000002B2E4087E60]  1317204 ms: Scavenge (reduce) 2046.2 (2082.6) -> 2045.5 (2082.6) MB, 4.7 / 0.0 ms  (average mu
= 0.115, current mu = 0.004) allocation failure
[2096:000002B2E4087E60]  1319918 ms: Mark-sweep (reduce) 2046.9 (2083.2) -> 2045.9 (2083.2) MB, 1411.0 / 0.1 ms  (+ 1043
.8 ms in 1247 steps since start of marking, biggest step 4.4 ms, walltime since start of marking 2482 ms) (average mu =
0.112, current

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6D9A630AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF6D99F2216 DSA_meth_get_flags+65542
 3: 00007FF6D99F30CD node::OnFatalError+301
 4: 00007FF6DA324B6E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6DA30F09D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6DA1B268C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF6DA1BF339 v8::internal::Heap::PublishPendingAllocations+1129
 8: 00007FF6DA1BC30A v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF6DA1AEF89 v8::internal::Heap::CollectGarbage+2137
10: 00007FF6DA1AD140 v8::internal::Heap::AllocateExternalBackingStore+2000
11: 00007FF6DA1D1A76 v8::internal::Factory::NewFillerObject+214
12: 00007FF6D9F04CB5 v8::internal::DateCache::Weekday+1797
13: 00007FF6DA3B2541 v8::internal::SetupIsolateDelegate::SetupHeap+494417
14: 00007FF6DA407404 v8::internal::SetupIsolateDelegate::SetupHeap+842260
15: 00007FF6DA4113AE v8::internal::SetupIsolateDelegate::SetupHeap+883134
16: 000002B2E5FA495E
```

**Comment by alcuadrado** [comment]
Did you modify anything in your project?

Try this to increase the memory limit: https://stackoverflow.com/a/64409997

**Comment by kajowy** [comment]
The same thing happens for me, the forked network works until eth_feehistory gets called with 1024 blocks as a parameter. 
Then hardhat hangs and eventually throw ```FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory```

**Comment by aliveli186** [comment]
> @aliveli186 are you also running `eth_feeHistory`?

I think any command locks the node. With me 2nd connection blocks it, like when MetaMask tries to connect.
I guess it's first commands are get block number, get balance kind of things...

**Comment by alcuadrado** [comment]
What do you mean by "locks the node"?

**Comment by aliveli186** [comment]
> What do you mean by "locks the node"?
> 
> Note that it only attends to 1 query at the time.

I mean node doesn't respond to RPC calls and after some time it throws this out of memory error.

**Comment by linyuliang** [comment]
I also encountered this problem...
I'm not sure if it's a metamask, or a hardhat problem...

**Comment by aliveli186** [comment]
With me it started few days ago after upgrading to v2.8.4. But I also upgraded other packages as well.
Now trying to set up another computer to be able to continue to work.

**Comment by linyuliang** [comment]
try downgrade your metamask to version 10.8.1. It works for me.

**Comment by alcuadrado** [comment]
Can you please create some way to reproduce it? A repo would be ideal.

Without one there's not much we can do.

**Comment by kajowy** [comment]
> try downgrade your metamask to version 10.8.1. It works for me.

Yes, it is a workaround but not a solution :)

**Comment by lcamargof** [comment]
Same happens to me, as soon as I try to run a transaction Metamask shows the approval with "0" estimated gas and the confirm button is grey out.

After a minute I got this from the console:

```eth_feeHistory

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/reportbug

eth_feeHistory

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/reportbug


<--- Last few GCs --->

[43427:0x148008000]   148387 ms: Mark-sweep 3894.3 (4131.1) -> 3880.6 (4129.5) MB, 3263.3 / 0.5 ms  (average mu = 0.246, current mu = 0.167) task scavenge might not succeed
[43427:0x148008000]   153287 ms: Mark-sweep 3896.7 (4129.9) -> 3883.5 (4130.0) MB, 2650.6 / 0.4 ms  (average mu = 0.361, current mu = 0.459) task scavenge might not succeed```

**Comment by aliveli186** [comment]
As @linyuliang stated it seems to be a MetaMask issue.

I was working on `Microsoft Edge Version 98.0.1108.50 (Official build) (64-bit)` with `MetaMask Version 10.9.2` installed.
This version of MetaMask on Edge browser is causing the error but it works fine on Chrome.

I removed the extension from Edge and I noticed that `10.9.2` version is no longer the latest version for Edge (probably removed due to bugs like that), there is `MetaMask Version 10.7.1` as the latest version and it works fine with Edge.
For now I don't have issues.

**Comment by aliveli186** [comment]
@lcamargof Try to reset the account because when u spawn a new node the account's nonce value stays as it was on the previous node. On a new node it has to start from 0 again.

Probably the gas estimation problem is due to this nonce mismatch.

`MetaMask: "Settings-> Advanced -> Reset Account"`

**Comment by lcamargof** [comment]
> @lcamargof Try to reset the account because when u spawn a new node the account's nonce value stays as it was on the previous node. On a new node it has to start from 0 again.
> 
> Probably the gas estimation problem is due to this nonce mismatch.
> 
> `MetaMask: "Settings-> Advanced -> Reset Account"`

Thanks! but I'm familiar with that issue, this is def related to Metamask, I'll try to downgrade it on chrome and see if it solves the issue.

Also something weird, if I cancel the TX the hardhat instance doesn't run out of memory but metamask will refuse to connect to localhost even if I restart the hardhat node.

**Comment by aliveli186** [comment]
> Also something weird, if I cancel the TX the hardhat instance doesn't run out of memory but metamask will refuse to connect to localhost even if I restart the hardhat node.

If it can't connect your node probably is not responding like with my case. Try installing MetaMask on a second browser and check if connects from there but I doubt, node is dead. If you wait long enough I think you'll receive the out of memory error on your node window.

**Comment by gregegan** [comment]
Just sharing I'm experiencing the same issues that got introduced recently in the past week. I cannot get hardhat to function at all due to these issues, tried bumping my node memory too

**Comment by lcamargof** [comment]
Related issue on the metamask repo https://github.com/MetaMask/metamask-extension/issues/13638

Changing the chainId is another workaround

**Comment by alcuadrado** [comment]
This problem seems to be related to MM now using `eth_feeHistory`. We'll investigate this asap.

**Comment by coostendorp** [comment]
In case anyone is in desperate need to get past this, I did a very dirty patch on the file
`node_modules/hardhat/internal/hardhat-network/provider/modules/eth.js`
in the function `_feeHistoryAction` so the function starts with:
```
    async _feeHistoryAction(blockCount, newestBlock, rewardPercentiles) {
        var _a;
        if (!this._node.isEip1559Active()) {
            throw new errors_1.InvalidInputError(`eth_feeHistory is disabled. It only works with the London hardfork or a later one.`);
        }
        return {
            oldestBlock: '0xd67c1e',
            baseFeePerGas: [ '0x53f71a32', '0x497836ec' ],
            gasUsedRatio: [ 0 ],
            reward: [ [ '0x0', '0x0' ] ]
        }
```
The values are arbitrary (copied from a successful invocation of the function) and I didnt care much about them (yet). Replace them as you see fit.

If you use patch-package you can also put the patch file (rename to remove .txt extension) in the /patches folder : [hardhat+2.8.4.patch.txt](https://github.com/NomicFoundation/hardhat/files/8101568/hardhat%2B2.8.4.patch.txt)

**Comment by alcuadrado** [comment]
No concrete update yet. We identified where this is coming from, but not the root of the problem.

**Comment by peculiarity** [comment]
Hello everyone,
Today after I did some investigation, I manage to create a workaround by downgrading MM to 10.7.1 which is the version before the latest `Arrow Glacier` hard fork that happened on 9th Dec. 
I successfully managed to work with my application and create transactions. I also noticed that the problem appeared after this `eth_feeHistory` command was introduced. 
P.S. In version 10.7.1 I noticed that `eth_feeHistory` was not called. In the latest version 10.9.3 it was constantly called.

**Comment by 0xAeni** [comment]
As @peculiarity points out, my setup basically stopped working around the latest `Arrow Glacier` update.
I haven't upgraded any dependencies.

My issues are similar to @aliveli186 and can be reproduced by the steps outlined in his comment.

Tried downgrading MM to 10.7.1 as @peculiarity suggested, but that didn't work for me. 
I also noticed `eth_feeHistory` being called a lot, starting MM `10.9.3`.  

When i upgrade Hardhat to the latest `2.9.0` version, I'm also experiencing the GC errors. 

Currently I'm unable to properly fork mainnet using hardhat completely. 

Toggling my hardhat neworks `chainId` config between `1337` and `31337` seems to introduce more issues than it solves.

**Comment by rafinskipg** [comment]
We started experiencing the same errors recently, without upgrading anything, on the server side using a hardhat fork, we see eth_feeHistory being called and nothing responding

**Comment by gregegan** [comment]
@alcuadrado could you share another update out on this by the end of the week?

**Comment by rafinskipg** [comment]
does anyone knows of a solution for this? all of our workflow depends on hardhat working  :S

**Comment by alcuadrado** [comment]
**Update:** We can now reproduce this reliably and have identified the source of the problem. We are exploring different ways to fix it.

**Comment by alcuadrado** [comment]
This was fixed in [v2.9.1](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.9.1)

**Comment by aliveli186** [comment]
Using hardhat v2.9.1 still receiving "JavaScript heap out of memory"

```
eth_sendTransaction

  Known transaction: 0xf2058cd7a668f4c45be36a740783b165f6608f8fe196f841bfaf62be8ddb4fe5

eth_sendTransaction

  Known transaction: 0xbf5ad8fc6c03895a4febd3fe7d0114879ecc4c08cf653da7c5d1404f0a58b2f6

eth_sendTransaction

  Known transaction: 0xed83bb58813f8c5d009e63dc42dae5723b0d1a1c91daf47ed2b6fb63ecbb7f32

eth_sendTransaction

  Known transaction: 0x0bc69c5d25221d1df9785fe54002fb757599f59cea97558fdef20e4ac2789464

eth_sendTransaction

  Known transaction: 0xbc9bb7e4ec14230c8623ade4004dee27caedef837ae3d346d3726bd4295fbb68

eth_blockNumber
eth_getBlockByNumber
eth_feeHistory (4)

<--- Last few GCs --->

[10228:0000022C94A8BB90]  1718742 ms: Scavenge (reduce) 2040.6 (2078.7) -> 2039.9 (2078.7) MB, 3.2 / 0.0 ms  (average mu = 0.390, current mu = 0.390) allocation failure
[10228:0000022C94A8BB90]  1718982 ms: Scavenge (reduce) 2040.7 (2078.7) -> 2040.1 (2078.7) MB, 3.3 / 0.0 ms  (average mu = 0.390, current mu = 0.390) allocation failure
[10228:0000022C94A8BB90]  1719046 ms: Scavenge (reduce) 2040.8 (2078.7) -> 2040.2 (2079.2) MB, 3.6 / 0.0 ms  (average mu = 0.390, current mu = 0.390) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF75766401F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF7575F3146 DSA_meth_get_flags+65542
 3: 00007FF7575F3FFD node::OnFatalError+301
 4: 00007FF757F25ADE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF757F1000D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF757DB35FC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF757DC02A9 v8::internal::Heap::PublishPendingAllocations+1129
 8: 00007FF757DBD27A v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF757DAFEF9 v8::internal::Heap::CollectGarbage+2137
10: 00007FF757DB370B v8::internal::Heap::FinalizeIncrementalMarkingAtomically+267
11: 00007FF757DA7E8F v8::base::CPU::is_fp64_mode+415
12: 00007FF757584C3F v8::CFunctionInfo::HasOptions+22111
13: 00007FF757583456 v8::CFunctionInfo::HasOptions+15990
14: 00007FF7576C313B uv_async_send+331
15: 00007FF7576C28CC uv_loop_init+1292
16: 00007FF7576C2A6A uv_run+202
17: 00007FF757691B75 node::SpinEventLoop+309
18: 00007FF7575ABAC3 cppgc::internal::NormalPageSpace::linear_allocation_buffer+53827
19: 00007FF757628E8D node::Start+221
20: 00007FF7574488CC RC4_options+348108
21: 00007FF7584A49F8 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+14472
22: 00007FF96F347974 BaseThreadInitThunk+20
23: 00007FF97126A2F1 RtlUserThreadStart+33
```

**Comment by julianmrodri** [comment]
Facing this exact error anytime I do a `hardhat_reset` of the Mainnet Fork in CI (Github Actions). Any ideas how to fix? Is this just a dependency/version issue?

**Comment by alcuadrado** [comment]
Hey @julianmrodri,

Please make sure you are running the latest version and open a new issue with steps to reproduce it. This error message is a generic Out of memory Node.js error and is not very telling.
