### ISSUE TITLE
Hardhat Node does not resolve the chainId of a forked network correctly

### ISSUE THREAD

**Issue by RiccardoBiosas** [NomicFoundation/hardhat#2642]
Spinning up a hardhat node with a forked network does not set the correct chainId and it is currently not possible to override the chainId manually (see [here](https://github.com/NomicFoundation/hardhat/issues/2305))
i.e: ```npx hardhat node --fork ARBITRUM_MAINNET_ALCHEMY_RPC --no-deploy``` sets 31337 as a chainId rather than 42161.

**Comment by kasperpawlowski** [comment]
@RiccardoBiosas the issue was fixed in the latest 2.9.6 release. could you confirm?

**Comment by RayXpub** [comment]
This is still a relevant issue as from what I have experienced it still hasn't been fixed

**Comment by RiccardoBiosas** [comment]
@kasperpawlowski apologies for the belated reply. I have just tried it on the `2.9.9` release and I am still experiencing the same issue described in the OP

**Comment by fvictorio** [comment]
Hi, I'm sorry for the super late response, this issue kind of slipped through the cracks.

We don't (and won't, for security reasons) automatically use the same chain id as the remote network. Otherwise you could be signing a replayable transaction. In most cases this will be safe, but we are erring on the side of being paranoid here.

So, that being said, I think we should close this in favor of #2305? I'm going to tentatively do that, but please let me know if you disagree and I'll re-open.
