### ISSUE TITLE
ProviderError: the method has been deprecated: eth_accounts

### ISSUE THREAD

**Issue by fisherpro** [NomicFoundation/hardhat#5572]
### Version of Hardhat

2.22.7

### What happened?

I am not able to deploy my hardhat contracts when using newer providers. 

Running the following code:
```
import { ethers } from 'hardhat';
async function main() {
    const [deployer] = await ethers.getSigners();
}
```

With command:
`npx hardhat --network erigon run scripts/test.ts`

Produces this error:
```
ProviderError: the method has been deprecated: eth_accounts
    at HttpProvider.request (C:\src\node_modules\hardhat\src\internal\core\providers\http.ts:96:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getSigners (C:\src\node_modules\@nomicfoundation\hardhat-ethers\src\internal\helpers.ts:43:30)
    at async main (C:\src\scripts\deploy-all.ts:13:24)
```

This is the code in hardhat-ethers from the stack (helpers.ts). This is called all the time by high level functions such as ethers.getContractFactory()... :
```
export async function getSigners(
  hre: HardhatRuntimeEnvironment
): Promise<HardhatEthersSigner[]> {
  const accounts: string[] = await hre.ethers.provider.send("eth_accounts", []);

  const signersWithAddress = await Promise.all(
    accounts.map((account) => getSigner(hre, account))
  );

  return signersWithAddress;
}
```

My provider is a local instance of Erigon. I tried using Erigon 3 and 2.60.0 and both produced the above error.

On the Erigon side I see this error:
`WARN[08-03|21:48:26.995] [rpc] served    conn=10.0.0.74:60977 method=eth_accounts reqid=2 t=31.49µs err="the method has been deprecated: eth_accounts"`

Some articles:
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-personal
https://github.com/ethereum/go-ethereum/releases/tag/v1.11.0

Geth is also getting rid of these "personal" methods as well.
Thank you.

### Minimal reproduction steps

Run the below code against Geth or Erigon without api personal defined.

```
import { ethers } from 'hardhat'
async function main() {
      const contractFact = await ethers.getContractFactory("UniswapV3Factory")
}
```

### Search terms

erigon personal eth_accounts deprecated

**Comment by kanej** [comment]
Taking a look at this, we think we should guard against the deprecation of the `eth_accounts` call and return `[]`. Effectively we fall back from there as though there where no unlocked accounts available from the node.

**Comment by borka-s** [comment]
Is there a workaround for this?

**Comment by kanej** [comment]
This has been fixed and released as part of [`hardhat-ethers@3.0.7`](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-ethers%403.0.7)

**Comment by fisherpro** [comment]
> Is there a workaround for this?

Yes. Just supply the signer when calling functions that interact with the chain. It's only when the signer is not supplied that eth_accounts was used to lookup the accounts.

**Comment by entin-hun** [comment]
> This has been fixed and released as part of [`hardhat-ethers@3.0.7`](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-ethers%403.0.7)
Unfortunately, the issue persists
![image](https://github.com/user-attachments/assets/1c550910-e78b-45c8-b1ec-bd007692b761)
