### ISSUE TITLE
No known hardfork for execution on historical block

### ISSUE THREAD

**Issue by Jonesyy3** [NomicFoundation/hardhat#7271]
### Version of Hardhat

3.0.0

### What happened?

Following https://hardhat.org/docs/reference/configuration I have tried to set up a forked chain in my hardhat.config.js.
It looks like this:

```ts
import type { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-ethers";
import hardhatViem from "@nomicfoundation/hardhat-viem";

import hardhatToolboxViemPlugin from "@nomicfoundation/hardhat-toolbox-viem";
import { configVariable } from "hardhat/config";
const MAINNET_URL_RPC =
  "https://eth-mainnet.g.alchemy.com/v2/<my api key>"; //temp substitution

const config: HardhatUserConfig = {
  plugins: [hardhatToolboxViemPlugin, hardhatViem],
  solidity: {
    compilers: [{ version: "0.8.28" }, { version: "0.4.19" }],
  },
  networks: {
    hardhat: {
      type: "edr-simulated",
      chainId: 31337,
      forking: {
        url: MAINNET_URL_RPC,
      },
    },
    sepolia: {
      type: "http",
      chainType: "l1",
      url: configVariable("SEPOLIA_RPC_URL"),
      accounts: [configVariable("SEPOLIA_PRIVATE_KEY")],
    },
  },
};

export default config;
```

I then wrote a simple script (following a youtube tutorial from a few years ago, but modernising it. its purpose to to get the pool address from aave (contract addresses and their abi/interfaces were taken from https://aave.com/docs/resources/addresses

```ts
async function getPoolAddressesProvider(account: any) {
  const poolAddressesProvider = await viem.getContractAt(
    "IPoolAddressesProvider",
    "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e",
    { client: { wallet: account } }
  );
  const poolAddress = await poolAddressesProvider.read.getPool();
  console.log(`pool adress: ${poolAddress}`);
  const pool = await viem.getContractAt(
    "IPool",
    "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",
    { client: { wallet: account } }
  );

  return pool;
}
```

Note: 'account' in this function comes from: const [deployer] = await viem.getWalletClients();

The issue i am having is :

```shell
Unhandled promise rejection:

CallExecutionError: Missing or invalid parameters.
Double check you have provided the correct parameters.

Raw Call Arguments:
  to:    0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e
  data:  0x026b1d5f

Details: No known hardfork for execution on historical block 23188683 (relative to fork block number 23188683) in chain with id 1. The node was not configured with a hardfork activation history.
Version: viem@2.34.0
    at getCallError (/Users/adamjones/Desktop/blockchain/hardhat-defi/node_modules/viem/utils/errors/getCallError.ts:42:10)
    at call (/Users/adamjones/Desktop/blockchain/hardhat-defi/node_modules/viem/_esm/actions/public/call.js:149:15)
    at async main (/Users/adamjones/Desktop/blockchain/hardhat-defi/scripts/aaveBorrow.ts:8:18) {
  cause: InvalidInputRpcError: Missing or invalid parameters.
  Double check you have provided the correct parameters.
```

I've checked through the docs and it seems that if i omit blockNumber, it will use the latest (which i believe is fine) and it will default to 'prague' which should also be fine. The parameters error on viem is a red herring i believe as ive confirmed the function does not need any p 
arameters and the issue is coming from hardhat

Additional information:
bypassing hardhat config and using solely viem (from alchemy docs) works:

```ts
  const client = createPublicClient({
    chain: mainnet,
    transport: http(
      MAINNET_URL_RPC
    ),
  });

  const block = await client.getBlock({
    blockNumber: 123456n,
  });

  console.log(block);
```

### Minimal reproduction steps

Create new hardhat v3 project
add the config setup as above
create a basic script as detailed above
use command "npx hardhat run scripts/aaveBorrow.ts --network hardhat"

### Search terms

No known hardfork for execution on historical block configuration v3 forking

**Comment by VanillaScent** [comment]
Facing the same issue when launching a forked node.

`npx hardhat node --fork https://eth-mainnet.g.alchemy.com/v2/<API_KEY>`

any ignition deployments and most interactions with the node face `eth_call` failures
```

eth_chainId
hardhat_metadata
eth_accounts
hardhat_getAutomine
eth_chainId
eth_getBlockByNumber
eth_getTransactionCount (3)
eth_getBlockByNumber (2)
eth_call

  No known hardfork for execution on historical block 23221106 (relative to fork block number 23221106) in chain with id 1. The node was not configured with a hardfork activation history.
```

Same issues arise when using the node for development in Viem DAPPs,
have not tested other libraries.

The same configuration but using the `--network hardhat` network configuration in `hardhat.config.ts` seems to run tests fine when forking, but then we are unable to use the node for other development aspects.

**Comment by fvictorio** [comment]
I can confirm this is a bug. The simplest workaround until we fix it is to mine a block immediately after starting the network, for example:

```js
const { networkHelpers, viem } = await hre.network.connect()
await networkHelpers.mine();

// your original code here
```

**Comment by kanej** [comment]
This has been fixed in the `Hardhat@3.0.3` release: https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%403.0.3

**Comment by geauser** [comment]
@kanej Still an issue in `hardhat@3.0.6`. With this network config:

```ts
["base-fork"]: {
  type: "edr-simulated",
  forking: {
    url: "https://mainnet.base.org"
  },
}
```

I'm still getting this: `Details: No known hardfork for execution on historical block 36188108 (relative to fork block number 36188108) in chain with id 8453. The node was not configured with a hardfork activation history.`

Caused by using viem public client:

```ts
const { viem } = await hre.network.connect();
const publicClient = await viem.getPublicClient();

return publicClient.readContract({
  address: createXAddress,
  abi,
  functionName: "computeCreate3Address",
  args: [salt]
});
```

However if I replace `viem.getPublicClient()` with a regular `createPublicClient` usage the issue goes away.

**Comment by adrian-gierakowski** [comment]
getting the same error for `https://sepolia.base.org` with hardhat 3.0.6

**Comment by geauser** [comment]
I managed to get rid of the issue by making sure I only connect once to a given network and mine immediately after connecting as @fvictorio mentioned here https://github.com/NomicFoundation/hardhat/issues/7271#issuecomment-3223995752 

```ts
import hre from "hardhat";
import { NetworkConnection } from "hardhat/types/network";

export let connections: Record<string, Promise<NetworkConnection> | NetworkConnection> = {};

export const getConnection = async (network = "default") => {
  if (connections[network]) return connections[network];
  connections[network] = hre.network.connect(network);
  if (network.includes("fork")) { // Only if your forked networks have 'fork' in their name
    const { networkHelpers } = await connections[network];
    await networkHelpers.mine();
  }
  return connections[network];
};
```
